Docs folder standardization and other fixes
yiisoft/app-console pull request #25
Opened 2024-04-14 14:17 UTC by luizcmarin

2024-04-23 11:31 UTC, samdark requested changes

2024-04-23 11:31 UTC, samdark commented on README.md
>  The template comes with ready to use [Codeception](https://codeception.com/) configuration.
That is to go into internals.

2024-04-23 11:31 UTC, samdark commented on docs/internals.md
> +## Unit testing
App templates are different: https://github.com/yiisoft/app-console/tree/master/.github/workflows i.e. no unit testing, no mutation testing and Codeception as testing entry point.

2024-04-24 13:04 UTC, luizcmarin commented on docs/internals.md
> +## Unit testing
remove ## Rector too

2024-04-24 20:00 UTC, samdark approved these changes

2024-04-24 20:00 UTC, merged